#!/usr/bin/env bash

DOTFILES_DIR=$(pwd)
TARGET_DIR="$HOME"
PKG=$1

stow_target() {
	local pkg=$1
	# Handle special permissions
	case "$pkg" in
		"gnupg")
			mkdir -p -m 700 "$HOME/.gnupg"
			;;
		"ssh")
			mkdir -p -m 700 "$HOME/.ssh"
			;;
	esac

	stow --restow -t "$TARGET_DIR" \
			--ignore='^\.' \
			--ignore='README\.md' \
			--ignore='install' \
			--no-folding \
			--verbose \
			"$pkg"

		hook="$DOTFILES_DIR/$package/install"
    if [[ -x "$hook" ]]; then
        echo "Running installation hook for $package..."
        if ! "$hook"; then
            echo "Something went wrong in $package install hook"
        fi
    fi
}

if [[ -n $PKG ]]; then
	echo "Installing $PKG dotfiles"
	stow_target "$PKG"
	exit 0
fi

echo "Installing dotfiles"
for dir in ./*/; do
    package=$(basename "$dir")

    # Ignore dot folders
    [[ "$package" == .* ]] && continue

    echo "Stowing $package package"
    stow_target "$package"
done
echo "Installation finished"
