#!/bin/zsh
for plugin in "${zsh_plugins[@]}"; do
    local name="${plugin##*/}"
    local plugin_path="$base_dir/$name"
    local repo_url="https://github.com/$plugin"
    
    if [[ ! -d $plugin_path ]]; then
        print "Installing $name..."
        git clone --depth 1 $repo_url $plugin_path
    fi
done
