#!/bin/zsh
for plugin in "${zsh_plugins[@]}"; do
		local name="${plugin##*/}"
		local plugin_path="$XDG_DATA_HOME/zsh/plugins/$name"

		if [[ ! -d $plugin_path ]]; then
				print "Cannot update $name"
				continue
		fi
		print "Updating $name..."
		git -C $plugin_path fetch --all
		git -C $plugin_path reset --hard origin/master
done

source-zsh-plugins
